import { Box } from "@chakra-ui/react";
import bgImage from "./../public/bg.jpg";
import Head from "next/head";
import { useRouter } from "next/router";
import { ChevronLeftIcon } from "@chakra-ui/icons";
import { IconButton } from "@chakra-ui/react";

function Layout({ children }) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Scrum 新手村</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box
          backgroundImage={bgImage.src}
          bgPos="center center"
          bgSize="cover"
          h="100vh"
          overflow="hidden"
        >
          {children}
          <IconButton
            icon={<ChevronLeftIcon />}
            position="fixed"
            left="2%"
            bottom="2%"
            borderRadius="50%"
            onClick={() => router.back()}
          />
        </Box>
      </main>
    </>
  );
}

export default Layout;
